FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o simulator ./cmd/simulator

FROM alpine:3.18
COPY --from=builder /app/simulator /usr/local/bin/simulator
CMD ["simulator"]