FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o processor ./cmd/processor

FROM alpine:3.18
COPY --from=builder /app/processor /usr/local/bin/processor
CMD ["processor"]