// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/events.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegionStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionStatsRequest) Reset() {
	*x = RegionStatsRequest{}
	mi := &file_proto_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionStatsRequest) ProtoMessage() {}

func (x *RegionStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionStatsRequest.ProtoReflect.Descriptor instead.
func (*RegionStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{0}
}

type RegionStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*RegionStat          `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionStatsResponse) Reset() {
	*x = RegionStatsResponse{}
	mi := &file_proto_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionStatsResponse) ProtoMessage() {}

func (x *RegionStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionStatsResponse.ProtoReflect.Descriptor instead.
func (*RegionStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{1}
}

func (x *RegionStatsResponse) GetStats() []*RegionStat {
	if x != nil {
		return x.Stats
	}
	return nil
}

type RegionStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	OrderCount    int64                  `protobuf:"varint,2,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	FailureCount  int64                  `protobuf:"varint,3,opt,name=failure_count,json=failureCount,proto3" json:"failure_count,omitempty"`
	Revenue       float64                `protobuf:"fixed64,4,opt,name=revenue,proto3" json:"revenue,omitempty"`
	AvgLatencyMs  float64                `protobuf:"fixed64,5,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionStat) Reset() {
	*x = RegionStat{}
	mi := &file_proto_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionStat) ProtoMessage() {}

func (x *RegionStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionStat.ProtoReflect.Descriptor instead.
func (*RegionStat) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{2}
}

func (x *RegionStat) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RegionStat) GetOrderCount() int64 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

func (x *RegionStat) GetFailureCount() int64 {
	if x != nil {
		return x.FailureCount
	}
	return 0
}

func (x *RegionStat) GetRevenue() float64 {
	if x != nil {
		return x.Revenue
	}
	return 0
}

func (x *RegionStat) GetAvgLatencyMs() float64 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

type EventCountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventCountsRequest) Reset() {
	*x = EventCountsRequest{}
	mi := &file_proto_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventCountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventCountsRequest) ProtoMessage() {}

func (x *EventCountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventCountsRequest.ProtoReflect.Descriptor instead.
func (*EventCountsRequest) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{3}
}

type EventCountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Counts        map[string]int64       `protobuf:"bytes,1,rep,name=counts,proto3" json:"counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventCountsResponse) Reset() {
	*x = EventCountsResponse{}
	mi := &file_proto_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventCountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventCountsResponse) ProtoMessage() {}

func (x *EventCountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventCountsResponse.ProtoReflect.Descriptor instead.
func (*EventCountsResponse) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{4}
}

func (x *EventCountsResponse) GetCounts() map[string]int64 {
	if x != nil {
		return x.Counts
	}
	return nil
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_proto_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{5}
}

func (x *StreamEventsRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type EventMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventMessage) Reset() {
	*x = EventMessage{}
	mi := &file_proto_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMessage) ProtoMessage() {}

func (x *EventMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMessage.ProtoReflect.Descriptor instead.
func (*EventMessage) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{6}
}

func (x *EventMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventMessage) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *EventMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EventMessage) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *EventMessage) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *EventMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_events_proto protoreflect.FileDescriptor

const file_proto_events_proto_rawDesc = "" +
	"\n" +
	"\x12proto/events.proto\x12\bshopfake\"\x14\n" +
	"\x12RegionStatsRequest\"A\n" +
	"\x13RegionStatsResponse\x12*\n" +
	"\x05stats\x18\x01 \x03(\v2\x14.shopfake.RegionStatR\x05stats\"\xaa\x01\n" +
	"\n" +
	"RegionStat\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12\x1f\n" +
	"\vorder_count\x18\x02 \x01(\x03R\n" +
	"orderCount\x12#\n" +
	"\rfailure_count\x18\x03 \x01(\x03R\ffailureCount\x12\x18\n" +
	"\arevenue\x18\x04 \x01(\x01R\arevenue\x12$\n" +
	"\x0eavg_latency_ms\x18\x05 \x01(\x01R\favgLatencyMs\"\x14\n" +
	"\x12EventCountsRequest\"\x93\x01\n" +
	"\x13EventCountsResponse\x12A\n" +
	"\x06counts\x18\x01 \x03(\v2).shopfake.EventCountsResponse.CountsEntryR\x06counts\x1a9\n" +
	"\vCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"-\n" +
	"\x13StreamEventsRequest\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\"\xb5\x01\n" +
	"\fEventMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp2\xf5\x01\n" +
	"\fEventService\x12M\n" +
	"\x0eGetRegionStats\x12\x1c.shopfake.RegionStatsRequest\x1a\x1d.shopfake.RegionStatsResponse\x12M\n" +
	"\x0eGetEventCounts\x12\x1c.shopfake.EventCountsRequest\x1a\x1d.shopfake.EventCountsResponse\x12G\n" +
	"\fStreamEvents\x12\x1d.shopfake.StreamEventsRequest\x1a\x16.shopfake.EventMessage0\x01B*Z(github.com/mrasyidgpfl/shopfake/proto/pbb\x06proto3"

var (
	file_proto_events_proto_rawDescOnce sync.Once
	file_proto_events_proto_rawDescData []byte
)

func file_proto_events_proto_rawDescGZIP() []byte {
	file_proto_events_proto_rawDescOnce.Do(func() {
		file_proto_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_events_proto_rawDesc), len(file_proto_events_proto_rawDesc)))
	})
	return file_proto_events_proto_rawDescData
}

var file_proto_events_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_events_proto_goTypes = []any{
	(*RegionStatsRequest)(nil),  // 0: shopfake.RegionStatsRequest
	(*RegionStatsResponse)(nil), // 1: shopfake.RegionStatsResponse
	(*RegionStat)(nil),          // 2: shopfake.RegionStat
	(*EventCountsRequest)(nil),  // 3: shopfake.EventCountsRequest
	(*EventCountsResponse)(nil), // 4: shopfake.EventCountsResponse
	(*StreamEventsRequest)(nil), // 5: shopfake.StreamEventsRequest
	(*EventMessage)(nil),        // 6: shopfake.EventMessage
	nil,                         // 7: shopfake.EventCountsResponse.CountsEntry
}
var file_proto_events_proto_depIdxs = []int32{
	2, // 0: shopfake.RegionStatsResponse.stats:type_name -> shopfake.RegionStat
	7, // 1: shopfake.EventCountsResponse.counts:type_name -> shopfake.EventCountsResponse.CountsEntry
	0, // 2: shopfake.EventService.GetRegionStats:input_type -> shopfake.RegionStatsRequest
	3, // 3: shopfake.EventService.GetEventCounts:input_type -> shopfake.EventCountsRequest
	5, // 4: shopfake.EventService.StreamEvents:input_type -> shopfake.StreamEventsRequest
	1, // 5: shopfake.EventService.GetRegionStats:output_type -> shopfake.RegionStatsResponse
	4, // 6: shopfake.EventService.GetEventCounts:output_type -> shopfake.EventCountsResponse
	6, // 7: shopfake.EventService.StreamEvents:output_type -> shopfake.EventMessage
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_events_proto_init() }
func file_proto_events_proto_init() {
	if File_proto_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_events_proto_rawDesc), len(file_proto_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_events_proto_goTypes,
		DependencyIndexes: file_proto_events_proto_depIdxs,
		MessageInfos:      file_proto_events_proto_msgTypes,
	}.Build()
	File_proto_events_proto = out.File
	file_proto_events_proto_goTypes = nil
	file_proto_events_proto_depIdxs = nil
}
